local config = {}

config.subsystems = {
    tires = {
        label = 'Pneus',
        defaultPartKey = 'tire_street_basic',
    },
    engine = {
        label = 'Motor',
        defaultPartKey = 'engine_stock',
    },
    brakes = {
        label = 'Freios',
        defaultPartKey = 'brake_street_basic',
    },
    drivetrain = {
        label = 'Tracao',
        defaultPartKey = 'drivetrain_factory',
    },
    suspension = {
        label = 'Suspensao',
        defaultPartKey = 'suspension_stock',
    },
    alignment = {
        label = 'Alinhamento',
        defaultPartKey = 'alignment_standard_service',
    },
    battery = {
        label = 'Bateria',
        defaultPartKey = 'battery',
    },
}

config.compatibilityGroups = {
    compact = {
        label = 'Compacto',
        categories = { 'compacts', 'coupes', 'cycles' },
        defaultDrivetrain = 'fwd',
    },
    sedan = {
        label = 'Sedan',
        categories = { 'sedans', 'muscle' },
        defaultDrivetrain = 'fwd',
    },
    sport = {
        label = 'Esportivo',
        categories = { 'sports', 'sportsclassics' },
        defaultDrivetrain = 'rwd',
    },
    super = {
        label = 'Super',
        categories = { 'super' },
        defaultDrivetrain = 'rwd',
    },
    suv = {
        label = 'SUV',
        categories = { 'suvs' },
        defaultDrivetrain = 'awd',
    },
    offroad = {
        label = 'Off-road',
        categories = { 'offroad' },
        defaultDrivetrain = 'awd',
    },
    utility = {
        label = 'Utilitario',
        categories = { 'vans', 'utility' },
        defaultDrivetrain = 'rwd',
    },
    truck = {
        label = 'Caminhao',
        categories = { 'commercial', 'industrial' },
        defaultDrivetrain = 'rwd',
    },
    bike = {
        label = 'Moto/Bike',
        categories = { 'motorcycles' },
        defaultDrivetrain = 'rwd',
    },
    air = {
        label = 'Aereo',
        categories = { 'helicopters', 'planes' },
        defaultDrivetrain = 'awd',
    },
    sea = {
        label = 'Aquatico',
        categories = { 'boats' },
        defaultDrivetrain = 'awd',
    },
    general = {
        label = 'Geral',
        categories = {},
        defaultDrivetrain = 'rwd',
    },
}

config.installationQuality = {
    self = {
        poor = { durabilityMultiplier = 0.82, performanceMultiplier = 0.9, failureRiskMultiplier = 1.35 },
        good = { durabilityMultiplier = 1.0, performanceMultiplier = 1.0, failureRiskMultiplier = 1.0 },
        premium = { durabilityMultiplier = 1.08, performanceMultiplier = 1.02, failureRiskMultiplier = 0.92 },
    },
    mechanic = {
        poor = { durabilityMultiplier = 0.9, performanceMultiplier = 0.95, failureRiskMultiplier = 1.15 },
        good = { durabilityMultiplier = 1.08, performanceMultiplier = 1.03, failureRiskMultiplier = 0.88 },
        premium = { durabilityMultiplier = 1.18, performanceMultiplier = 1.07, failureRiskMultiplier = 0.72 },
    },
}

config.serviceThresholds = {
    warning = 70,
    critical = 40,
    failure = 15,
}

config.wearSampling = {
    intervalMs = 8000,
    minDistanceKm = 0.08,
}

config.wearModel = {
    -- Normal RP use: repairs are meaningful, but parts do not disappear every few routes.
    targetLifespanKm = {
        tires = 3200,
        brakes = 6500,
        suspension = 8000,
        transmission = 10000,
        engine = 12500,
        battery = 15000,
    },
    maintenanceClassMultiplier = {
        light_work = 1.0,
        utility_work = 1.05,
        commercial = 1.1,
        heavy_duty = 1.2,
        light_sport = 1.08,
        sport = 1.12,
        exotic = 1.22,
        hyper = 1.35,
    },
    abuseWear = {
        impact = {
            engine = 0.010,
            battery = 0.010,
            transmission = 0.004,
            brakes = 0.003,
            suspension = 0.030,
            tires = 0.006,
        },
    },
    repairFatigue = {
        perKitRepair = 0.18,
        maxExtraWear = 1.0,
    },
    failure = {
        engineStopHealth = 8,
        transmissionStopHealth = 5,
        tirePunctureHealth = 12,
        tireBurstHealth = 2,
    },
}

config.healthDegradation = {
    healthyThreshold = 80.0,
    wornThreshold = 40.0,
    healthySlope = 0.0025,
    wornSlope = 0.0045,
    criticalSlope = 0.008,
    criticalFloor = 0.77,
}

config.servicePlan = {
    defaultIntervalKm = 2500,
    overdueGraceKm = 300,
    severeOverdueKm = 900,
    baseServiceCost = 1200,
    compatibilityCostMultiplier = {
        compact = 0.9,
        sedan = 1.0,
        sport = 1.25,
        super = 1.65,
        suv = 1.15,
        offroad = 1.2,
        utility = 1.1,
        truck = 1.45,
        bike = 0.7,
        air = 2.2,
        sea = 1.8,
        general = 1.0,
    },
}

config.recurringBilling = {
    intervalSeconds = 43200,
    latePenaltyMultiplier = 1.12,
    outstandingWearMultiplier = 1.08,
    severeOutstandingWearMultiplier = 1.16,
    premiumDebtBlockAmount = 8000,
    baseCost = 1800,
    compatibilityCostMultiplier = {
        compact = 0.85,
        sedan = 1.0,
        sport = 1.2,
        super = 1.6,
        suv = 1.1,
        offroad = 1.15,
        utility = 1.12,
        truck = 1.45,
        bike = 0.6,
        air = 2.0,
        sea = 1.7,
        general = 1.0,
    },
}

config.workshopEconomy = {
    installLaborBase = {
        self = 650,
        mechanic = 1750,
    },
    serviceLaborBase = {
        self = 450,
        mechanic = 1450,
    },
    tierMultiplier = {
        [0] = 0.9,
        [1] = 1.0,
        [2] = 1.2,
        [3] = 1.5,
        [4] = 1.9,
    },
    compatibilityCostMultiplier = {
        compact = 0.9,
        sedan = 1.0,
        sport = 1.2,
        super = 1.45,
        suv = 1.12,
        offroad = 1.15,
        utility = 1.08,
        truck = 1.3,
        bike = 0.65,
        air = 1.75,
        sea = 1.55,
        general = 1.0,
    },
    mechanicJobDiscount = 0.45,
    mechanicSelfDurationMultiplier = 0.82,
}

config.partsCatalog = {
    standard_tires = {
        key = 'standard_tires',
        label = 'Pneu Comum',
        category = 'tire',
        subsystem = 'tires',
        tier = 0,
        rarity = 'common',
        shopType = 'autoparts',
        price = 3000,
        installTimeSeconds = 18,
        selfInstallAllowed = true,
        baseDurability = 92,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            grip = 0.98,
            wet = 0.92,
            drift = 0.68,
            offroad = 0.58,
            wearRate = 1.04,
        },
    },
    truck_tire = {
        key = 'truck_tire',
        label = 'Pneu Reforcado',
        category = 'tire',
        subsystem = 'tires',
        tier = 1,
        rarity = 'uncommon',
        shopType = 'autoparts',
        price = 6000,
        installTimeSeconds = 24,
        selfInstallAllowed = true,
        baseDurability = 118,
        compatibilityGroups = { 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            grip = 0.96,
            wet = 0.93,
            drift = 0.58,
            offroad = 0.92,
            wearRate = 0.82,
        },
    },
    tire_street_basic = {
        key = 'tire_street_basic',
        label = 'Pneus Rua Comum',
        category = 'tire',
        subsystem = 'tires',
        tier = 0,
        rarity = 'common',
        shopType = 'autoparts',
        price = 3800,
        installTimeSeconds = 20,
        selfInstallAllowed = true,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            grip = 1.0,
            wet = 0.95,
            drift = 0.7,
            offroad = 0.65,
            wearRate = 1.0,
        },
    },
    tire_street_sport = {
        key = 'tire_street_sport',
        label = 'Pneus Rua Esportivo',
        category = 'tire',
        subsystem = 'tires',
        tier = 1,
        rarity = 'uncommon',
        shopType = 'autoparts',
        price = 7200,
        installTimeSeconds = 24,
        selfInstallAllowed = true,
        baseDurability = 98,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv' },
        effectProfile = {
            grip = 1.04,
            wet = 0.92,
            drift = 0.78,
            offroad = 0.62,
            wearRate = 1.05,
        },
    },
    tire_rain_pro = {
        key = 'tire_rain_pro',
        label = 'Pneus Chuva',
        category = 'tire',
        subsystem = 'tires',
        tier = 1,
        rarity = 'uncommon',
        shopType = 'autoparts',
        price = 7600,
        installTimeSeconds = 24,
        selfInstallAllowed = true,
        baseDurability = 98,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv' },
        effectProfile = {
            grip = 0.99,
            wet = 1.08,
            drift = 0.68,
            offroad = 0.62,
            wearRate = 0.97,
        },
    },
    tire_drift_pro = {
        key = 'tire_drift_pro',
        label = 'Pneus Drift Premium',
        category = 'tire',
        subsystem = 'tires',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 14800,
        installTimeSeconds = 28,
        selfInstallAllowed = false,
        baseDurability = 88,
        compatibilityGroups = { 'sport', 'super', 'sedan' },
        effectProfile = {
            grip = 0.92,
            wet = 0.78,
            drift = 1.16,
            offroad = 0.45,
            wearRate = 1.12,
        },
    },
    tire_offroad_pro = {
        key = 'tire_offroad_pro',
        label = 'Pneus Off-road',
        category = 'tire',
        subsystem = 'tires',
        tier = 1,
        rarity = 'uncommon',
        shopType = 'autoparts',
        price = 9800,
        installTimeSeconds = 26,
        selfInstallAllowed = true,
        baseDurability = 108,
        compatibilityGroups = { 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            grip = 0.96,
            wet = 0.95,
            drift = 0.65,
            offroad = 1.1,
            wearRate = 0.94,
        },
    },
    tire_race_premium = {
        key = 'tire_race_premium',
        label = 'Pneus Corrida Premium',
        category = 'tire',
        subsystem = 'tires',
        tier = 3,
        rarity = 'epic',
        shopType = 'premium_shop',
        price = 26500,
        installTimeSeconds = 30,
        selfInstallAllowed = false,
        baseDurability = 88,
        compatibilityGroups = { 'sport', 'super' },
        effectProfile = {
            grip = 1.1,
            wet = 0.78,
            drift = 0.88,
            offroad = 0.35,
            wearRate = 1.15,
        },
    },
    engine_package_stock = {
        key = 'engine_package_stock',
        label = 'Motor Original',
        category = 'engine_package',
        subsystem = 'engine',
        tier = 0,
        rarity = 'common',
        shopType = 'factory',
        price = 0,
        installTimeSeconds = 0,
        selfInstallAllowed = false,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck', 'bike' },
        effectProfile = {
            power = 1.0,
            heatTolerance = 1.0,
            wearRate = 1.0,
        },
    },
    brake_street_basic = {
        key = 'brake_street_basic',
        label = 'Kit de Freio Rua',
        category = 'brake_kit',
        subsystem = 'brakes',
        tier = 0,
        rarity = 'common',
        shopType = 'autoparts',
        price = 4200,
        installTimeSeconds = 18,
        selfInstallAllowed = true,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            braking = 1.0,
            fadeResistance = 1.0,
            wearRate = 1.0,
        },
    },
    drivetrain_factory = {
        key = 'drivetrain_factory',
        label = 'Conjunto de Tracao Original',
        category = 'drivetrain_conversion',
        subsystem = 'drivetrain',
        tier = 0,
        rarity = 'common',
        shopType = 'factory',
        price = 0,
        installTimeSeconds = 0,
        selfInstallAllowed = false,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck', 'bike' },
        effectProfile = {
            traction = 1.0,
            launch = 1.0,
            wearRate = 1.0,
        },
    },
    suspension_street_basic = {
        key = 'suspension_street_basic',
        label = 'Suspensao Rua',
        category = 'suspension_kit',
        subsystem = 'suspension',
        tier = 0,
        rarity = 'common',
        shopType = 'factory',
        price = 0,
        installTimeSeconds = 0,
        selfInstallAllowed = false,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            stability = 1.0,
            comfort = 1.0,
            wearRate = 1.0,
        },
    },
    alignment_standard_service = {
        key = 'alignment_standard_service',
        label = 'Alinhamento Padrao',
        category = 'alignment_service',
        subsystem = 'alignment',
        tier = 0,
        rarity = 'common',
        shopType = 'autoparts',
        price = 1800,
        installTimeSeconds = 12,
        selfInstallAllowed = true,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            precision = 1.0,
            tirePreservation = 1.0,
            wearRate = 1.0,
        },
    },
    ecu_sport_stage = {
        key = 'ecu_sport_stage',
        label = 'ECU Sport',
        category = 'ecu',
        subsystem = 'engine',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 16800,
        installTimeSeconds = 25,
        selfInstallAllowed = false,
        baseDurability = 96,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv' },
        effectProfile = {
            power = 1.045,
            throttle = 1.03,
            wearRate = 1.06,
        },
    },
    turbo_street_kit = {
        key = 'turbo_street_kit',
        label = 'Turbo Street',
        category = 'turbo',
        subsystem = 'engine',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 24500,
        installTimeSeconds = 30,
        selfInstallAllowed = false,
        baseDurability = 92,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'suv' },
        effectProfile = {
            power = 1.075,
            heatTolerance = 0.94,
            wearRate = 1.1,
        },
    },
    supercharger_street_kit = {
        key = 'supercharger_street_kit',
        label = 'Compressor Street',
        category = 'supercharger',
        subsystem = 'engine',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 27200,
        installTimeSeconds = 30,
        selfInstallAllowed = false,
        baseDurability = 94,
        compatibilityGroups = { 'sedan', 'sport', 'super', 'suv', 'truck' },
        effectProfile = {
            power = 1.085,
            torque = 1.08,
            wearRate = 1.1,
        },
    },
    radiator_heavy_duty = {
        key = 'radiator_heavy_duty',
        label = 'Radiador Reforcado',
        category = 'radiator',
        subsystem = 'engine',
        tier = 1,
        rarity = 'uncommon',
        shopType = 'autoparts',
        price = 6900,
        installTimeSeconds = 16,
        selfInstallAllowed = true,
        baseDurability = 108,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            heatTolerance = 1.12,
            wearRate = 0.92,
        },
    },
    filter_performance = {
        key = 'filter_performance',
        label = 'Filtro Performance',
        category = 'filter',
        subsystem = 'engine',
        tier = 1,
        rarity = 'common',
        shopType = 'autoparts',
        price = 3200,
        installTimeSeconds = 10,
        selfInstallAllowed = true,
        baseDurability = 96,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck', 'bike' },
        effectProfile = {
            airflow = 1.015,
            wearRate = 1.0,
        },
    },
    clutch_performance = {
        key = 'clutch_performance',
        label = 'Embreagem Performance',
        category = 'clutch',
        subsystem = 'drivetrain',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 14200,
        installTimeSeconds = 22,
        selfInstallAllowed = false,
        baseDurability = 98,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            launch = 1.06,
            wearRate = 0.96,
        },
    },
    suspension_sport_kit = {
        key = 'suspension_sport_kit',
        label = 'Suspensao Esportiva',
        category = 'suspension_kit',
        subsystem = 'suspension',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 15800,
        installTimeSeconds = 26,
        selfInstallAllowed = false,
        baseDurability = 96,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv' },
        effectProfile = {
            stability = 1.06,
            comfort = 0.94,
            wearRate = 1.03,
        },
    },
    drivetrain_conversion_awd = {
        key = 'drivetrain_conversion_awd',
        label = 'Kit Conversao AWD',
        category = 'drivetrain_conversion',
        subsystem = 'drivetrain',
        tier = 3,
        rarity = 'epic',
        shopType = 'premium_shop',
        price = 54000,
        installTimeSeconds = 40,
        selfInstallAllowed = false,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'super', 'suv', 'offroad', 'utility', 'truck' },
        effectProfile = {
            drivetrain = 'awd',
            traction = 1.035,
            wearRate = 1.06,
        },
    },
    drivetrain_conversion_fwd = {
        key = 'drivetrain_conversion_fwd',
        label = 'Kit Conversao FWD',
        category = 'drivetrain_conversion',
        subsystem = 'drivetrain',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 32000,
        installTimeSeconds = 34,
        selfInstallAllowed = false,
        baseDurability = 100,
        compatibilityGroups = { 'compact', 'sedan', 'sport', 'suv', 'utility' },
        effectProfile = {
            drivetrain = 'fwd',
            traction = 1.0,
            launch = 0.99,
            wearRate = 0.98,
        },
    },
    drivetrain_conversion_rwd = {
        key = 'drivetrain_conversion_rwd',
        label = 'Kit Conversao RWD',
        category = 'drivetrain_conversion',
        subsystem = 'drivetrain',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 41000,
        installTimeSeconds = 36,
        selfInstallAllowed = false,
        baseDurability = 98,
        compatibilityGroups = { 'sedan', 'sport', 'super', 'utility', 'truck' },
        effectProfile = {
            drivetrain = 'rwd',
            traction = 0.98,
            launch = 1.02,
            wearRate = 1.02,
        },
    },
    drift_tires = {
        key = 'drift_tires',
        label = 'Pneus de Drift',
        category = 'tire',
        subsystem = 'tires',
        tier = 2,
        rarity = 'rare',
        shopType = 'premium_shop',
        price = 12000,
        installTimeSeconds = 28,
        selfInstallAllowed = false,
        baseDurability = 88,
        compatibilityGroups = { 'sport', 'super', 'sedan' },
        effectProfile = {
            grip = 0.92,
            wet = 0.78,
            drift = 1.16,
            offroad = 0.45,
            wearRate = 1.12,
        },
    },
    racing_tires = {
        key = 'racing_tires',
        label = 'Pneus de Corrida',
        category = 'tire',
        subsystem = 'tires',
        tier = 3,
        rarity = 'epic',
        shopType = 'premium_shop',
        price = 15000,
        installTimeSeconds = 30,
        selfInstallAllowed = false,
        baseDurability = 88,
        compatibilityGroups = { 'sport', 'super' },
        effectProfile = {
            grip = 1.1,
            wet = 0.78,
            drift = 0.88,
            offroad = 0.35,
            wearRate = 1.15,
        },
    },
    drag_tires = {
        key = 'drag_tires',
        label = 'Pneus de Arrancada',
        category = 'tire',
        subsystem = 'tires',
        tier = 3,
        rarity = 'epic',
        shopType = 'premium_shop',
        price = 14000,
        installTimeSeconds = 30,
        selfInstallAllowed = false,
        baseDurability = 86,
        compatibilityGroups = { 'sport', 'super', 'sedan' },
        effectProfile = {
            grip = 1.08,
            wet = 0.72,
            drift = 0.7,
            offroad = 0.34,
            wearRate = 1.12,
        },
    },
    performance_kit_drag = {
        key = 'performance_kit_drag',
        label = 'Kit Drag Race',
        category = 'performance_kit',
        subsystem = 'performance_kit',
        tier = 3,
        rarity = 'epic',
        shopType = 'premium_shop',
        price = 55000,
        installTimeSeconds = 45,
        selfInstallAllowed = false,
        baseDurability = 84,
        compatibilityGroups = { 'sedan', 'sport', 'super' },
        effectProfile = {
            drive = 1.28,
            speed = 1.04,
            shift = 1.22,
            traction = 0.78,
            suspension = 1.10,
            wearRate = 1.18,
        },
    },
    performance_kit_drift = {
        key = 'performance_kit_drift',
        label = 'Kit Drift',
        category = 'performance_kit',
        subsystem = 'performance_kit',
        tier = 3,
        rarity = 'epic',
        shopType = 'premium_shop',
        price = 48000,
        installTimeSeconds = 42,
        selfInstallAllowed = false,
        baseDurability = 82,
        compatibilityGroups = { 'sedan', 'sport', 'super' },
        effectProfile = {
            drive = 1.10,
            speed = 0.97,
            shift = 1.10,
            traction = 0.72,
            suspension = 0.88,
            wearRate = 1.20,
        },
    },
    performance_kit_race = {
        key = 'performance_kit_race',
        label = 'Kit Corrida',
        category = 'performance_kit',
        subsystem = 'performance_kit',
        tier = 3,
        rarity = 'epic',
        shopType = 'premium_shop',
        price = 72000,
        installTimeSeconds = 48,
        selfInstallAllowed = false,
        baseDurability = 88,
        compatibilityGroups = { 'sport', 'super' },
        effectProfile = {
            drive = 1.16,
            speed = 1.06,
            shift = 1.16,
            brake = 1.16,
            traction = 1.08,
            suspension = 1.10,
            wearRate = 1.10,
        },
    },
}

config.shopTypes = {
    autoparts = { label = 'Autopecas', shopId = 'tycoon_maintenance_autoparts' },
    premium_shop = { label = 'Oficina Premium', shopId = 'tycoon_maintenance_premium' },
    factory = { label = 'Origem de Fabrica' },
}

config.mechanicJobs = {
    'mechanic',
    'bennys',
}

config.autoPartsCounters = {
    {
        key = 'city_autoparts',
        label = 'Autopecas Centro',
        coords = vec4(342.99, -1298.26, 32.51, 48.0),
        pedModel = 's_m_m_autoshop_02',
        scenario = 'WORLD_HUMAN_CLIPBOARD',
        interactionDistance = 2.2,
    },
    {
        key = 'north_autoparts',
        label = 'Autopecas Norte',
        coords = vec4(2748.0, 3473.0, 55.67, 65.0),
        pedModel = 's_m_m_autoshop_02',
        scenario = 'WORLD_HUMAN_CLIPBOARD',
        interactionDistance = 2.2,
    },
}

config.workshops = {
    {
        key = 'bennys_official',
        label = "Oficina Oficial Benny's",
        coords = vec4(-211.45, -1324.62, 30.89, 89.0),
        pedModel = 's_m_y_xmech_01',
        scenario = 'WORLD_HUMAN_CLIPBOARD',
        interactionDistance = 2.5,
        serviceRadius = 18.0,
    },
    {
        key = 'sandy_official',
        label = 'Oficina Oficial Sandy',
        coords = vec4(1174.68, 2640.41, 37.75, 5.0),
        pedModel = 's_m_y_xmech_01',
        scenario = 'WORLD_HUMAN_CLIPBOARD',
        interactionDistance = 2.5,
        serviceRadius = 18.0,
    },
}

return config
