TycoonCore = TycoonCore or {}

TycoonCore.VehicleMatrix = {
    -- BIKES (Starter)
    ['cruiser'] = { label = 'Cruiser', branch = 'land', tier = 0, price = 0, capacity = 1, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['bmx'] = { label = 'BMX', branch = 'land', tier = 0, price = 800, capacity = 1, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    
    -- CIVILIAN IMPORTS (Core Work Tier 1 / Status Light)
    ['miata3'] = { label = '1989 Mazda Miata NA', branch = 'land', tier = 1, price = 22000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['na6'] = { label = 'Mazda MX-5 Miata (NA6C)', branch = 'land', tier = 1, price = 24000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['honcrx91'] = { label = 'Honda CRX SiR 1991', branch = 'land', tier = 1, price = 28000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['srt4'] = { label = 'Dodge Neon SRT-4', branch = 'land', tier = 1, price = 32000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['svx'] = { label = '1996 Subaru Alcyone SVX', branch = 'land', tier = 1, price = 35000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['katana'] = { label = '2019 Suzuki Katana', branch = 'land', tier = 0, price = 35000, capacity = 1, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'light_sport', maintenanceClass = 'light_sport', cash = true, financing = false, rental = false },
    ['fto'] = { label = 'Mitsubishi FTO GP Version-R', branch = 'land', tier = 1, price = 35000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['17civict'] = { label = '2017 Honda Civic Touring', branch = 'land', tier = 1, price = 42000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['cam8tun'] = { label = '2018 Toyota Camry XSE', branch = 'land', tier = 1, price = 45000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['gsxr19'] = { label = '2019 Suzuki GSX-R1000R', branch = 'land', tier = 0, price = 45000, capacity = 1, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'light_sport', maintenanceClass = 'light_sport', cash = true, financing = false, rental = false },
    ['z32'] = { label = 'Nissan 300ZX Z32', branch = 'land', tier = 1, price = 45000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['84rx7k'] = { label = '1984 Mazda RX-7 Stanced Version', branch = 'land', tier = 1, price = 48000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['e34'] = { label = '1995 BMW M5 E34', branch = 'land', tier = 1, price = 48000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['sl500'] = { label = '1995 Mercedes-Benz SL500', branch = 'land', tier = 1, price = 48000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['180sx'] = { label = 'Nissan 180SX Type-X', branch = 'land', tier = 1, price = 48000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['fc3s'] = { label = 'Mazda RX7 FC3S', branch = 'land', tier = 1, price = 52000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['maj350'] = { label = 'Nissan Fairlady Z Z33', branch = 'land', tier = 1, price = 52000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['80B4'] = { label = '1995 Audi Cabriolet (RS2) (B4)', branch = 'land', tier = 1, price = 55000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['s14'] = { label = '1998 Nissan Silvia K', branch = 'land', tier = 1, price = 55000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['gs350'] = { label = 'Lexus GS 350', branch = 'land', tier = 1, price = 55000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['mk2100'] = { label = 'Toyota Mark II JZX100', branch = 'land', tier = 1, price = 55000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['760li04'] = { label = '2004 BMW 760Li Individual (E66/PFL)', branch = 'land', tier = 1, price = 58000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['is350mod'] = { label = '2014 Lexus IS 350', branch = 'land', tier = 1, price = 62000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['tltypes'] = { label = 'Acura TL Type-S', branch = 'land', tier = 1, price = 62000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['ap2'] = { label = 'Honda S2000 AP2', branch = 'land', tier = 1, price = 62000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['nis15'] = { label = 'Nissan Silvia S15 Spec-R', branch = 'land', tier = 1, price = 65000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['subwrx'] = { label = '2004 Subaru Impreza WRX STI', branch = 'land', tier = 1, price = 68000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['ns350'] = { label = 'Nissan 350z Stardast', branch = 'land', tier = 1, price = 68000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['s8d2'] = { label = '1998 Audi S8 (D2/PFL)', branch = 'land', tier = 1, price = 72000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['16challenger'] = { label = '2016 Dodge Challenger', branch = 'land', tier = 1, price = 72000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['subisti08'] = { label = '2008 Subaru WRX STi', branch = 'land', tier = 1, price = 78000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['16charger'] = { label = '2016 Dodge Charger', branch = 'land', tier = 1, price = 78000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['aaq4'] = { label = '2017 Audi A4 Quattro ABT', branch = 'land', tier = 1, price = 78000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['majfd'] = { label = 'Mazda RX-7 FD', branch = 'land', tier = 1, price = 78000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['audquattros'] = { label = '1983 Audi Quattro Sport', branch = 'land', tier = 1, price = 85000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['cats'] = { label = '2016 Cadillac ATS-V Coupe', branch = 'land', tier = 1, price = 85000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['tmodel'] = { label = '2018 Tesla Model 3', branch = 'land', tier = 1, price = 85000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['nzp'] = { label = 'Nissan 370z Pandem', branch = 'land', tier = 1, price = 85000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['esprit02'] = { label = '2002 Lotus Esprit V8', branch = 'land', tier = 1, price = 89000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },
    ['fk8'] = { label = '2018 Honda Civic Type-R (FK8)', branch = 'land', tier = 1, price = 89000, capacity = 4, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'basic_work', maintenanceClass = 'light_work', cash = true, financing = true, rental = true },

    -- HYPERCARS (Status Hyper)
    ['svj63'] = { label = 'Lamborghini Aventador SVJ', branch = 'land', tier = 6, price = 1150000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['regalia'] = { label = 'Quartz Regalia 723', branch = 'land', tier = 6, price = 1250000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['it18'] = { label = '2017 Italdesign Zerouno', branch = 'land', tier = 6, price = 1450000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['senna'] = { label = '2019 McLaren Senna', branch = 'land', tier = 6, price = 1480000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['lambose'] = { label = 'Lamborghini Sesto Elemento', branch = 'land', tier = 6, price = 2100000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['gtr96'] = { label = '1996 McLaren F1 GTR', branch = 'land', tier = 6, price = 2400000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['mig'] = { label = 'Ferrari Enzo', branch = 'land', tier = 6, price = 2800000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['wmfenyr'] = { label = 'W-Motors Fenyr Supersport', branch = 'land', tier = 6, price = 2800000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['mcst'] = { label = '2020 McLaren Speedtail', branch = 'land', tier = 6, price = 2900000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['laferrari'] = { label = '2015 Ferrari LaFerrari', branch = 'land', tier = 6, price = 3200000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['lykan'] = { label = 'W-Motors Lykan HyperSport', branch = 'land', tier = 6, price = 3200000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['veneno'] = { label = '2013 Lamborghini Veneno LP750-4', branch = 'land', tier = 6, price = 3400000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['regera'] = { label = 'Koenigsegg Regera', branch = 'land', tier = 6, price = 3600000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['agerars'] = { label = '2017 Koenigsegg Agera RS', branch = 'land', tier = 6, price = 3800000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['fxxk'] = { label = 'Ferrari FXX-K Hybrid Hypercar', branch = 'land', tier = 6, price = 4500000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },
    ['bolide'] = { label = '2020 Bugatti Bolide', branch = 'land', tier = 6, price = 4800000, capacity = 1, layer = 'status_hyper', requiredLicense = 'driver', insuranceClass = 'hyper', maintenanceClass = 'hyper', cash = true, financing = false, rental = false },

    -- RACE (Status Light)
    ['sultanrs'] = { label = 'Karin Sultan RS', branch = 'land', tier = 1, price = 145000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['elegy'] = { label = 'Annis Elegy RH8', branch = 'land', tier = 1, price = 165000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['jester'] = { label = 'Dinka Jester', branch = 'land', tier = 1, price = 185000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['kuruma'] = { label = 'Karin Kuruma', branch = 'land', tier = 1, price = 195000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['ninef'] = { label = 'Obey 9F', branch = 'land', tier = 1, price = 210000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['comet2'] = { label = 'Pfister Comet', branch = 'land', tier = 1, price = 220000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['banshee'] = { label = 'Bravado Banshee', branch = 'land', tier = 1, price = 240000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['massacro'] = { label = 'Dewbauchee Massacro', branch = 'land', tier = 1, price = 280000, capacity = 3, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },

    -- SPORTS IMPORTS (Status Light)
    ['m3e36'] = { label = '1997 BMW M3 E36', branch = 'land', tier = 2, price = 65000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['corvettec5z06'] = { label = 'Chevrolet Corvette C5 Z06', branch = 'land', tier = 2, price = 90000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['m3e92'] = { label = '2008 BMW M3 e92', branch = 'land', tier = 2, price = 98000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['mustang50th'] = { label = '2015 Ford Mustang GT 50 Years', branch = 'land', tier = 2, price = 110000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['toysupmk4'] = { label = '1998 Toyota Supra Turbo (A80)', branch = 'land', tier = 2, price = 115000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['ttrs'] = { label = '2010 Audi TT RS', branch = 'land', tier = 2, price = 115000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['rcf'] = { label = '2015 Lexus RCF', branch = 'land', tier = 2, price = 115000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['z419'] = { label = '2019 BMW Z4 M40i', branch = 'land', tier = 2, price = 120000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['99viper'] = { label = '1999 Dodge Viper GTS ACR', branch = 'land', tier = 2, price = 125000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['m2'] = { label = '2016 BMW M2', branch = 'land', tier = 2, price = 125000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['czr1'] = { label = '2009 Chevrolet Corvette ZR1', branch = 'land', tier = 2, price = 135000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['models'] = { label = '2016 Tesla Model S P90D', branch = 'land', tier = 2, price = 135000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['2020ss'] = { label = '2020 Chevrolet Camaro SS', branch = 'land', tier = 2, price = 135000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['m3f80'] = { label = '2015 BMW M3 (F80)', branch = 'land', tier = 2, price = 145000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['teslapd'] = { label = '2017 Tesla Model S Prior design', branch = 'land', tier = 2, price = 148000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['m4f82'] = { label = '2015 BMW M4 F82', branch = 'land', tier = 2, price = 155000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['718caymans'] = { label = 'Porsche 718 Cayman S', branch = 'land', tier = 2, price = 155000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['c7'] = { label = '2014 Chevrolet Corvette C7 Stingray', branch = 'land', tier = 2, price = 165000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['chr20'] = { label = 'Dodge Charger Hellcat Widebody 2021', branch = 'land', tier = 2, price = 165000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['skyline'] = { label = 'Nissan Skyline GT-R (BNR34)', branch = 'land', tier = 2, price = 165000, capacity = 4, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['demon'] = { label = '2018 Dodge Challenger SRT Demon', branch = 'land', tier = 2, price = 195000, capacity = 5, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['m6f13'] = { label = 'BMW M6 F13 Shadow Line', branch = 'land', tier = 2, price = 195000, capacity = 5, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['rs6'] = { label = '2016 Audi RS6 C7', branch = 'land', tier = 3, price = 220000, capacity = 5, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['stingray'] = { label = '2020 Chevrolet Corvette C8 Stingray', branch = 'land', tier = 3, price = 220000, capacity = 5, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['rs72020'] = { label = '2020 Audi RS7', branch = 'land', tier = 3, price = 245000, capacity = 5, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['ast'] = { label = '2013 Aston Martin Vanquish', branch = 'land', tier = 3, price = 265000, capacity = 6, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['gtr'] = { label = '2017 Nissan GTR', branch = 'land', tier = 3, price = 280000, capacity = 6, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['taycan'] = { label = '2020 Porsche Taycan Turbo S', branch = 'land', tier = 3, price = 290000, capacity = 6, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['gtrc'] = { label = '2017 R35 Nissan GTR Convertible', branch = 'land', tier = 3, price = 295000, capacity = 6, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },
    ['tr22'] = { label = '2020 Tesla Roadster', branch = 'land', tier = 3, price = 320000, capacity = 6, layer = 'status_light', requiredLicense = 'driver', insuranceClass = 'sport', maintenanceClass = 'sport', cash = true, financing = false, rental = false },

    -- SUPERCARS IMPORTS (Status Super)
    ['mp412c'] = { label = 'McLaren MP4-12C', branch = 'land', tier = 5, price = 380000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['fct'] = { label = '2015 Ferrari California T', branch = 'land', tier = 5, price = 390000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['f430s'] = { label = 'Ferrari F430 Scuderia', branch = 'land', tier = 5, price = 410000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['amggtrr20'] = { label = '2020 Mercedes-Benz AMG GT-R', branch = 'land', tier = 5, price = 420000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['r8ppi'] = { label = '2013 Audi R8 V10', branch = 'land', tier = 5, price = 430000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['fgt'] = { label = '2005 Ford GT', branch = 'land', tier = 5, price = 450000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['yFe458i1'] = { label = 'Ferrari 458 Italia', branch = 'land', tier = 5, price = 450000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['r820'] = { label = '2020 Audi R8', branch = 'land', tier = 5, price = 480000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['650s'] = { label = 'McLaren 650S Coupe', branch = 'land', tier = 5, price = 480000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['wraith'] = { label = 'Rolls-Royce Wraith', branch = 'land', tier = 5, price = 480000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['yFe458s1'] = { label = 'Ferrari 458 Spider', branch = 'land', tier = 5, price = 495000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['675lt'] = { label = '2016 McLaren 675LT Coupe', branch = 'land', tier = 5, price = 520000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['dawnonyx'] = { label = '2016 Rolls-Royce Dawn Onyx', branch = 'land', tier = 5, price = 520000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['huracanst'] = { label = 'Lamborghini Huracan Super Trofeo', branch = 'land', tier = 5, price = 540000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['yFe458i2'] = { label = 'Ferrari 458 Speciale', branch = 'land', tier = 5, price = 580000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['rculi'] = { label = 'Rolls Royce Cullinan', branch = 'land', tier = 5, price = 580000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['lp670sv'] = { label = '2009 Lamborghini Murcielago SV', branch = 'land', tier = 5, price = 590000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['cgt'] = { label = '2003 Porsche Carrera GT (980)', branch = 'land', tier = 5, price = 620000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['yFe458s2'] = { label = 'Ferrari 458 Speciale Aperta', branch = 'land', tier = 5, price = 640000, capacity = 2, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['720s'] = { label = '2017 McLaren 720S', branch = 'land', tier = 5, price = 650000, capacity = 1, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['lp700r'] = { label = '2013 Lamborghini Aventador LP700-4', branch = 'land', tier = 5, price = 680000, capacity = 1, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['rrphantom'] = { label = '2018 Rolls-Royce Phantom VIII', branch = 'land', tier = 5, price = 680000, capacity = 1, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['gt17'] = { label = '2017 Ford GT', branch = 'land', tier = 5, price = 750000, capacity = 1, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['yFeF12T'] = { label = 'Ferrari F12 TRS Roadster', branch = 'land', tier = 5, price = 790000, capacity = 1, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['yFeF12A'] = { label = 'Ferrari F60 America', branch = 'land', tier = 5, price = 850000, capacity = 1, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },
    ['f812'] = { label = '2018 Ferrari 812 Superfast', branch = 'land', tier = 5, price = 890000, capacity = 1, layer = 'status_super', requiredLicense = 'driver', insuranceClass = 'exotic', maintenanceClass = 'exotic', cash = true, financing = false, rental = false },

    -- SUV & OFF-ROAD (Premium Functional / Core Work Tier 2-3)
    ['lrrr'] = { label = '1973 Land Rover Range Rover', branch = 'land', tier = 2, price = 32000, capacity = 2, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['jeepreneg'] = { label = 'Jeep Renegade', branch = 'land', tier = 2, price = 38000, capacity = 5, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['09tahoe'] = { label = '2009 Chevrolet Tahoe', branch = 'land', tier = 2, price = 45000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['jeep2012'] = { label = '2012 Jeep Wrangler', branch = 'land', tier = 2, price = 48000, capacity = 5, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['Safari97'] = { label = '1997 Nissan Patrol Super Y60', branch = 'land', tier = 2, price = 58000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['ram2500'] = { label = '2015 Dodge RAM 2500', branch = 'land', tier = 2, price = 65000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['f150'] = { label = '2012 Ford F150 SVT Raptor R', branch = 'land', tier = 2, price = 68000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['v250'] = { label = 'Mercedes-Benz V-class 250', branch = 'land', tier = 2, price = 68000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['15tahoe'] = { label = '2015 Chevrolet Tahoe', branch = 'land', tier = 2, price = 75000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['rrevoque'] = { label = 'Range Rover Evoque', branch = 'land', tier = 2, price = 85000, capacity = 5, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['srt8'] = { label = '2015 Jeep SRT-8', branch = 'land', tier = 2, price = 95000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['nissantitan17'] = { label = '2017 Nissan Titan Warrior', branch = 'land', tier = 2, price = 95000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['raptor2017'] = { label = '2017 Ford Raptor', branch = 'land', tier = 2, price = 98000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['xc90'] = { label = 'Volvo XC90 T8', branch = 'land', tier = 2, price = 110000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['tahoe21'] = { label = '2021 Chevrolet Tahoe RST', branch = 'land', tier = 2, price = 115000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['wildtrak'] = { label = '2021 Ford Bronco Wildtrak', branch = 'land', tier = 2, price = 115000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['vxr'] = { label = '2016 Toyota Land Cruiser VXR', branch = 'land', tier = 3, price = 125000, capacity = 8, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['sq72016'] = { label = '2016 Audi SQ7', branch = 'land', tier = 2, price = 135000, capacity = 5, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['trx'] = { label = '2017 Dodge RAM 1500 Rebel TRX', branch = 'land', tier = 3, price = 135000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'utility_work', cash = true, financing = true, rental = true },
    ['pm19'] = { label = '2019 Porsche Macan Turbo', branch = 'land', tier = 2, price = 145000, capacity = 5, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['fpacehm'] = { label = 'Jaguar F-pace 2017 Hamann', branch = 'land', tier = 2, price = 145000, capacity = 5, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['gl63'] = { label = 'Mercedes-Benz GL63 AMG', branch = 'land', tier = 2, price = 145000, capacity = 5, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['trhawk'] = { label = '2018 Jeep Cherokee Trackhawk', branch = 'land', tier = 2, price = 148000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['teslax'] = { label = '2016 Tesla Model X P90D', branch = 'land', tier = 3, price = 155000, capacity = 6, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['levante'] = { label = 'Maserati Levante', branch = 'land', tier = 3, price = 155000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['q820'] = { label = '2020 Audi Q8 50TDI', branch = 'land', tier = 3, price = 165000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['p90d'] = { label = 'Tesla Model X Unplugged', branch = 'land', tier = 3, price = 165000, capacity = 6, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['cesc21'] = { label = '2021 Cadillac Escalade', branch = 'land', tier = 3, price = 175000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['pcs18'] = { label = '2018 Porsche Cayenne S', branch = 'land', tier = 3, price = 185000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['rrst'] = { label = 'Range Rover Vogue Startech', branch = 'land', tier = 3, price = 195000, capacity = 6, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['G65'] = { label = '2013 Mercedes-Benz G65 AMG', branch = 'land', tier = 3, price = 210000, capacity = 6, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['rsvr16'] = { label = '2016 Range Rover Sport SVR', branch = 'land', tier = 3, price = 220000, capacity = 6, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['amdbx'] = { label = 'Aston Martin DBX Carbon', branch = 'land', tier = 3, price = 280000, capacity = 6, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['bbentayga'] = { label = 'Bentley Bentayga', branch = 'land', tier = 3, price = 310000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },
    ['urus'] = { label = 'Lamborghini Urus', branch = 'land', tier = 3, price = 360000, capacity = 3, layer = 'premium_functional', requiredLicense = 'driver', insuranceClass = 'premium_utility', maintenanceClass = 'premium_utility', cash = true, financing = true, rental = false },

    -- TRANSPORT AIR (Core Work)
    ['maverick'] = { label = 'Maverick', branch = 'air', tier = 1, price = 320000, capacity = 2, layer = 'core_work', requiredLicense = 'heli', insuranceClass = 'aviation', maintenanceClass = 'aviation', cash = true, financing = true, rental = true },
    ['frogger'] = { label = 'Frogger', branch = 'air', tier = 2, price = 420000, capacity = 3, layer = 'core_work', requiredLicense = 'heli', insuranceClass = 'aviation', maintenanceClass = 'aviation', cash = true, financing = true, rental = true },
    ['swift'] = { label = 'Swift', branch = 'air', tier = 3, price = 620000, capacity = 4, layer = 'core_work', requiredLicense = 'heli', insuranceClass = 'aviation', maintenanceClass = 'aviation', cash = true, financing = true, rental = true },
    ['cargobob'] = { label = 'Cargobob', branch = 'air', tier = 5, price = 980000, capacity = 8, layer = 'core_work', requiredLicense = 'heli', insuranceClass = 'aviation', maintenanceClass = 'aviation', cash = true, financing = true, rental = true },

    -- TRANSPORT LAND (Core Work)
    ['bison'] = { label = 'Vapid Bison Cargo', branch = 'land', tier = 2, price = 65000, capacity = 8, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'commercial', maintenanceClass = 'commercial', cash = true, financing = true, rental = true },
    ['mule'] = { label = 'Maibatsu Mule', branch = 'land', tier = 4, price = 120000, capacity = 12, layer = 'core_work', requiredLicense = 'truck', insuranceClass = 'commercial', maintenanceClass = 'commercial', cash = true, financing = true, rental = true },
    ['pounder'] = { label = 'MTL Pounder', branch = 'land', tier = 5, price = 210000, capacity = 16, layer = 'core_work', requiredLicense = 'truck', insuranceClass = 'commercial', maintenanceClass = 'commercial', cash = true, financing = true, rental = true },
    ['barracks'] = { label = 'HVY Barracks', branch = 'land', tier = 5, price = 290000, capacity = 20, layer = 'core_work', requiredLicense = 'truck', insuranceClass = 'commercial', maintenanceClass = 'commercial', cash = true, financing = true, rental = true },

    -- TRANSPORT WATER (Core Work)
    ['dinghy'] = { label = 'Nagasaki Dinghy', branch = 'water', tier = 1, price = 110000, capacity = 2, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'marine', maintenanceClass = 'marine', cash = true, financing = true, rental = true },
    ['marquis'] = { label = 'Dinka Marquis', branch = 'water', tier = 3, price = 180000, capacity = 6, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'marine', maintenanceClass = 'marine', cash = true, financing = true, rental = true },
    ['suntrap'] = { label = 'Shitzu Suntrap', branch = 'water', tier = 2, price = 260000, capacity = 3, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'marine', maintenanceClass = 'marine', cash = true, financing = true, rental = true },
    ['tug'] = { label = 'Buckingham Tug', branch = 'water', tier = 5, price = 310000, capacity = 12, layer = 'core_work', requiredLicense = 'driver', insuranceClass = 'marine', maintenanceClass = 'marine', cash = true, financing = true, rental = true },
}

local hashCache = {}

function TycoonCore.GetVehicleData(model)
    local modelStr = tostring(model):lower()
    return TycoonCore.VehicleMatrix[modelStr]
end

function TycoonCore.GetVehicleDataByHash(hash)
    if hashCache[hash] then return hashCache[hash] end

    for model, data in pairs(TycoonCore.VehicleMatrix) do
        if joaat(model) == hash then
            hashCache[hash] = data
            return data
        end
    end
    return nil
end

return TycoonCore.VehicleMatrix
